CrawlerSystem/models/log.py
# -*- coding: utf-8 -*-
#日志类模型
#
from django.db import models
from django.db import connection,connections
import datetime, time, json, calendar
from util import datetime_to_str,trace_msg
from .base import (BaseModelMixin,
                   CacheAttribute,
                   CachedClassAttribute)

try:
    import cPickle as pickle
except ImportError:
    import pickle
import uuid, json, hashlib
from settings import get_app_label,PROJECT_ROOT
import traceback
import os,glob
from collections import OrderedDict



class Log(models.Model,BaseModelMixin):
    '''日志基本模型
    '含有空值的列很难进行查询优化，因为它们使得索引、索引的统计信息以及比较运算更加复杂。你应该用0、一个特殊的值或者一个空串代替空值。
    '''
    log_time = models.DateTimeField('记录时间',auto_now_add=True,db_index=True)
    log_type = models.IntegerField('类型',default=0)
    log_tag = models.IntegerField('标记',default=0,null=True)
    log_user = models.IntegerField('角色ID',default=0,null=True,db_index=True)
    log_name = models.CharField('角色名',max_length=100,default='123', null=True,blank=False)
    log_server = models.IntegerField('服务器ID',default=0, null=True)
    log_level = models.IntegerField('等级',null=True,default=0)
    log_previous = models.CharField('之前值',max_length=200, default='',null=True, blank=True)
    log_now = models.CharField('现在值',max_length=200, default='',null=True, blank=True)
    log_relate = models.CharField('流水标识',max_length=32,default='',null=True,db_index=True)
    f1 = models.CharField(max_length=100, default='',null=True, blank=True)
    f2 = models.CharField(max_length=100, default='',null=True, blank=True)
    f3 = models.CharField(max_length=100, default='',null=True, blank=True)
    f4 = models.CharField(max_length=100, default='',null=True, blank=True)
    f5 = models.CharField(max_length=100, default='',null=True, blank=True)
    f6 = models.TextField(default='',null=True, blank=True)
    f7 = models.CharField(max_length=100, default='',null=True, blank=True)
    f8 = models.TextField(default='',null=True, blank=True)
    log_channel = models.IntegerField('渠道ID',default=0, null=True,blank=True)
    log_data = models.IntegerField('数据',null=True,default=0)
    log_result = models.IntegerField('结果',null=True,default=0)
    
    def __unicode__(self):
        return '%d_%d_%s' % (self.log_type, self.log_user, self.log_time.strftime('%Y-%m-%d'))

    def log_time_str(self):
        return datetime_to_str(self.log_time) 
    
    @classmethod
    def get_create_table_sql(cls,table_name):
        sql = 'CREATE TABLE IF NOT EXISTS  %s LIKE %s;' % (table_name,cls._Meta.db_table)
        return sql
    
    class _Meta: # 防止使用log表时失去元表名
        db_table = u'log_0_new'
        app_label = get_app_label()

    Meta = _Meta

class LogDefineMixin(object):
    
    @classmethod
    def get_truncate_table_sqls(cls):
        sqls = []
        log_defs = cls.objects.filter(status=cls.Status.NORMAL)
        for ld in log_defs:
            if ld.key == 'statistic_date':
                continue 
            sqls.append('truncate table %s;' % ld.table_name)
        return sqls
        
    def get_create_table_sql(self):
        return Log.get_create_table_sql(self.table_name)
    
    def get_create_index_sqls(self):
        sqls = []
        for f in self.get_index_fields():
            
            index_name = '%s_%s_index' % (self.table_name,f['filed_name'])
            sql = "CREATE INDEX `%s` ON `%s` (%s);" % (index_name,self.table_name,f['filed_name'])
            sqls.append(sql)
        return sqls
    
    def get_index_fields(self):
        index_fields = []
        for k,v in self.config.iteritems():
            if v.get('db_index','') and v.get('verbose_name','').strip() :
                v['filed_name'] = k
                index_fields.append(v)
        return index_fields
    
    @classmethod
    def get_create_table_sqls(cls,is_center=False):
        '''获取需要创建表的sql
        '''
        status = cls.Status.CENTER if is_center else cls.Status.NORMAL
        sqls = []
        for t in cls.objects.filter(status=status):
            sqls.append(t.get_create_table_sql())
        return sqls
    
    def get_field_name_by_verbose_name(self,verbose_name):
        for field_name,config in self.config:
            if verbose_name == config['verbose_name'] :
                return field_name
            
            
class LogDefine(models.Model,BaseModelMixin,LogDefineMixin):
    '''日志类定义
    '''
    
    class Status:
            NORMAL = 0
            CENTER = 1
            
    TYPE_CHOICES  = ((Status.NORMAL,'分服'),(Status.CENTER,'中央服'))
    
    key = models.CharField('日志表名',max_length=20,db_index=True)
    name = models.CharField('日志名',max_length=50)
    remark = models.CharField('备注',max_length=1000)
    status = models.IntegerField(default=0,choices=TYPE_CHOICES)
    _config = models.TextField('配置')
    trigger =  models.TextField('触发器sql',default="",null=False)
    
    #  这里未来兼容sql文件导入和mysqldb执行的sql 处理有点乱, 到时再改
    def get_other_sqls(self,is_sql_file=False):
        '''获取其他sql
        @is_sql_file:是否sql文件用的
        '''
        sqls = []
        sp = ';'
        the_cut_sp = '\\'
        if '//' in self.trigger:
            sp = '//'
        for sql in self.trigger.split(sp):
            if the_cut_sp in sql :
                if  is_sql_file:
                    sql = sql.replace(the_cut_sp,'')
                else:
                    sql = ''
            elif not is_sql_file:
                    sql = sql.replace('$$','')
            if sql:
                sqls.append('%s' % sql)
        return sqls
    
    @property
    def config(self):
        _r = {}
        field_config = self.default_config()
        try:
            _r = json.loads(self._config)
            field_config.update(_r)
        except:
            pass
        _r = field_config
        sort_dict = OrderedDict(_r)
        sort_dict.keyOrder = sorted(_r.keys(),reverse=True)
        return sort_dict
    
    @config.setter
    def config(self,obj_value):
        if isinstance(obj_value,dict):
            obj_value = json.dumps(obj_value)
        self._config = obj_value
    
    @CacheAttribute
    def json_config(self):
        return json.dumps(self.config, ensure_ascii=True)
    
    @property
    def table_name(self):
        return 'log_%s' % self.key.strip()
    
    def default_config(self):
        '''默认的日志类配置
        '''
        _d = {}
        for f in Log._meta.fields:
            if f.name.lower() == 'id':
                continue

            _d[f.name] = {"db_index":f.db_index,"verbose_name":f.verbose_name}
        return _d
     
        
    def save(self,*args,**kwargs):
        return super(LogDefine,self).save(*args,**kwargs)
    
    def __unicode__(self):
        return '%s' % self.key

    class Meta: 
        db_table = u'def_log'
        app_label = get_app_label()
        
        
    
        
class DictBaseType(object):
    '''基本字典类型
    '''
    NAME = '字典'
    DEFAULT_JSON = '{}'
    def __init__(self,dict_config):
        self.dict = dict_config
    def get_dict(self):
        return self.dict


class DBDictType(DictBaseType):
    '''数据表
    '''
    NAME = '数据表'
    DEFAULT_JSON = '{"table_name":"","key_name":"","value_name":""}'
    def get_dict(self):
        _r = {}
        sql = 'SELECT DISTINCT `{key_name}` a,`{value_name}` b FROM {table_name} LIMIT 2000;'
        sql = sql.format(**self.dict)
        cur = connections['read'].cursor()
        cur.execute(sql)
        for row in cur.fetchall():
            _r[str(row[0])] = row[1]
        return _r

ROOT_PATH = os.path.dirname(PROJECT_ROOT)
class FileDicType(DictBaseType):
    '''从文件内拿json
    '''
    NAME = '文件'
    DEFAULT_JSON = '{"file_path":"","key_name":"","value_name":""}'
    def get_dict(self):
        _r = {}
        the_file_path  = os.path.join(ROOT_PATH,self.dict['file_path'])
        try:
            with open(the_file_path,'rb') as fp:
                _r = the_dict_data = json.loads(fp.read() )
        except:
            pass
        return _r
    
    
from util import get_files_from_dir
class DirDictType(DictBaseType):
    '''目录里拿字典
    '''
    NAME = '目录'
    DEFAULT_JSON = '{"dir_path":"","key_name":"","value_name":""}'
    def get_dict(self):
        _r = {}
        the_dir_path  = os.path.join(ROOT_PATH,self.dict['dir_path'])

        try:
            if os.path.isdir(the_dir_path):
                for the_json_file in get_files_from_dir(the_dir_path,'.json'):

                    with open(the_json_file,'rb') as fp:
                        json_str = fp.read()
                        json_data = json.loads(json_str)
                        key_name = self.dict.get('key_name','')
                        value_name = self.dict.get('value_name','')
                        if key_name and value_name:
                            key = json_data.get(key_name,'')
                            value = json_data.get(value_name,'')
                            if key:
                                _r[key] =  value
        except:
            print the_dir_path
            traceback.print_exc()
        return _r 

def get_default_dict():
    return pickle.dumps({})

def get_default_key():
    return uuid.uuid4().hex
    

class DictDefine(models.Model,BaseModelMixin):   
    '''字典定义
    '''
    TYPE_DICT = {   0:DictBaseType,
                    1:DBDictType,
                    2:FileDicType,
                    3:DirDictType
                    }
  
    SELECT_CHOICES = [ (k,v.NAME,v.DEFAULT_JSON) for k,v in TYPE_DICT.iteritems() ]
    _TYPE_CHOICES = ( (k,v.NAME) for k,v in TYPE_DICT.iteritems() )

    name = models.CharField('字典名',max_length=100,blank=False) 

CrawlerSystem/models/role.py
# -*- coding: utf-8 -*-
#
#角色相关模型
#
#
from django.db import models
from .resource import Resource
from .base import (BaseModelMixin,
                   CacheAttribute,
                   CachedClassAttribute)
import time,datetime,urllib
import traceback
from settings import get_app_label
     
     
class RoleManagerMixin(object):
    
    
    def add_resource_member(self,name,id):
        '''增加资源对象
        @name  资源名
        @id    资源对象id
        '''
        resource_objs = self.resource.all().filter(name=name)
        if resource_objs:
            resource_objs[0].add_member(id)
            resource_objs[0].save()
        
    def get_resource(self,name):
        resource_ids = self.resource.get(name=name).members
        return Resource.resource_map[name].objects.filter(id__in=resource_ids).distinct()   
    
    
    def create_resource(self,name,id_list):
        '''角色创建资源
        @资源名
        @id列表
        '''
        if not self.id:#新建时没有对象,先保存一下
            self.save()
        resource,created = Resource.objects.get_or_create(name = name,role_id=self.id)
        resource.members = id_list
        resource.save()
        self.resource.add(resource)
            
        
class Role(models.Model,BaseModelMixin,RoleManagerMixin):
    '''角色模型
    '''
    
    class RoleType:
        ADMIN =   0   #管理员
        NORMAL =  1   #普通账号
    
    TYPE_CHOICES = ((RoleType.NORMAL,'普通'),(RoleType.ADMIN,'管理员'))
    
    name = models.CharField('角色名',max_length=50,unique=True,db_index=True)
    parent_name = models.CharField('主管名',max_length=50,default='',db_index=True)
    resource = models.ManyToManyField(Resource,verbose_name='资源对象') 
    type = models.IntegerField('角色类型',default=1, choices=TYPE_CHOICES)
    remark = models.CharField('角色描述',default='',max_length=1000)
    
    @CacheAttribute
    def resource_ids(self):
        _r = {}
        for r in self.resource.all():
            _r[r.name] = r.members
        return _r
    
    @property
    def is_manager(self):
        return self.type == self.RoleType.ADMIN
    
    
    def save(self,*args,**kwargs):
        super(Role,self).save(*args,**kwargs)    
        
    def delete(self,*args,**kwargs):
        for r in self.resource.all():
            r.delete()
        self.resource.clear()
        super(Role,self).delete(*args,**kwargs)
   
    def __unicode__(self):
        return '%s' % self.name
   
    class Meta:
        db_table = u'role_new'
        app_label = get_app_label()


Resource.register('role',Role)


templates/system/admin_list.html
{% extends "base.html" %}

{% block header%}
<title>用户列表</title>
{% endblock %}

{% block content %}
{% with model_name='Admin' url_prefix='/system/admin/admin_' %}
<div >
	<ul id="nav-list" class="nav nav-tabs" >
			  <li class="active"  >
			  	<a href="{{url_prefix}}list" data-toggle="tab">用户列表</a>
			  </li>
			  <li >
			  	<a href="/system/role/role_list">角色列表</a>
			  </li>
	</ul>
	<!-- 按钮工具条 -->
	<div id='datatable_toolbar'>
		<div class="btn-toolbar pull-right">
			<div class="btn-group ">
				<a class="btn btn btn-success " onclick="add{{model_name}}(this)">
					<i class="fa fa-plus-square"></i>添加
				</a>
			</div>
			<div class="btn-group">
				
				<a class="btn btn btn-primary " onclick="edit{{model_name}}(this)">
					<i class="fa fa-edit"></i>编辑
				</a>
				<a data-toggle="dropdown" class="btn  btn-primary dropdown-toggle">
					<span class="menu-arrow arrow_carrot-down"></span>
				</a>
				<ul class="dropdown-menu">
					<li>
						<a  class="" onclick="remove{{model_name}}(this)">
							<i class="fa fa-trash-o"></i> 删除
						</a>
						<a  class="" onclick="recover{{model_name}}(this)">
							<i class="fa fa-share-alt "></i> 恢复
						</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
	<!--  -->
	<table  class="table table-striped table-advance table-hover table-bordered datatable" data-toolbar='datatable_toolbar' data-group-by-index='[5]'>
		<thead>
		<tr>
			<th width="60">
				<input type="checkbox" checkbox-area='{{model_name}}_area'  >
			</th>
			<th >ID</th>
			<th>别名</th>
			<th>登录名</th>
			<th>拥有角色</th>
			<th>状态</th>
			<th>登录次数</th>
			<th>登录IP</th>
			<th>最近时间</th>
		</tr>
		</thead>
		<tbody id="{{model_name}}_area">
		{%for item in list_record%}
		<tr trid='{{item.id}}'>
			<td>
				<input type="checkbox"  value="{{item.id}}" name="id">
			</td>
			<td>{{item.id}}</td>
			<td><a href="{{url_prefix}}edit?id={{item.id}}" class="openDialog">{{item.alias}}</a></td>
			<td>{{item.username}}</td>
			<td>
				{% with  item.role.all as roles %}
					{%if roles%}
						{% for r in roles%}
							<a href="/system/role/role_edit?id={{r.id}}" class="openDialog">{{r.name}}{%if not forloop.last %}</a>,{%endif%}
						{% endfor%}
					{%else%}
						没有角色
					{%endif%}
				
				{%endwith%}
			</td>
			<td>{{item.get_status_display}}</td>
			<td>{{item.login_count}}</td>
			<td>{{item.last_ip}}</td>
			<td>{{item.last_time|date:"Y-m-d H:i:s"}}</td>
		</tr>
		{%endfor%}
		</tbody>
	</table>
</div>
{%endwith%}
{% endblock %}

templates/system/menu_edit.html
{% extends "base.html" %}

{% block header%}
<title>功能模块编辑</title>

{% endblock %}

{% block content %}
{% with model_name='Menu' url_prefix='/system/menu/menu_'  %}
<div class="bar">
	<a href="{{url_prefix}}edit?parent_id={{menu.parent_id}}">功能列表</a> -> 功能模块编辑
	<div class="buttons">
		<a class="btn btn-app btn-grey btn-xs radius-4 pull-right submit">保存</a>
	</div>
</div>

<form action="{{url_prefix}}save?id={{menu.id}}" method="post">
	<table class="form">

		<tr>
			<th>模块名称：</th><td><input type="text" name="name" value="{{menu.name}}" /></td>
		</tr>
		<tr>
			<th>父级：</th><td>
			<select name="parent_id" >
				{%if menu.parent_id == 0 %}
					<option value="0">顶级</option>
				{%else%}
					{%for item in list_menu%}
						{%ifnotequal item.id menu.id%}
						<option value="{{item.id}}" {%ifequal item.id menu.parent_id%}selected="selected"{%endifequal%}>{{item.name}}</option>
						{%endifnotequal%}
					{%endfor%}
				{%endif%}
			</select>
		</td>
		</tr>

	<tr>
		<th>排序：</th><td><input type="text" name="order" value="{{menu.order}}" /></td>
	</tr>
	<tr>
		<th>菜单显示：</th>
		<td>
		<!-- <input type="checkbox" name="is_show" value="1"{%ifequal menu.is_show 1%} checked="checked"{%endifequal%}/> -->
		<label class="inline">
			<input type="checkbox" value="1" {%ifequal menu.is_show 1%} checked="checked"{%endifequal%} offval="No" id="stock" name="is_show" role="checkbox" class="FormElement ace ace-switch ace-switch-5"><span class="lbl"></span>
		</label>
		</td>
	</tr>
	<tr>
		<th>记录日志：</th><td>
		<!-- <input type="checkbox" name="is_log" value="1"{%ifequal menu.is_log 1%} checked="checked"{%endifequal%}/> -->
		<label class="inline">
			<input type="checkbox"  value="1" {%ifequal menu.is_log 1%} checked="checked"{%endifequal%} offval="No" id="stock" name="is_log" role="checkbox" class="FormElement ace ace-switch ace-switch-5"><span class="lbl"></span>
		</label>
		</td>
	</tr>

	<tr>
		<th>模块路径：</th><td><input type="text" name="url" value="{{menu.url}}" class="input-xxlarge"/></td>
	</tr>
	<tr>
		<th>模块图标：</th><td>

		<input id="menu_icon" class="pull-left" type="text" name="icon" value="{{menu.icon}}" />
		<a href="javascript:;" onclick="openwindow('/static/cus-icons.html?eid=menu_icon','menu_icon_select',0.3,0.3)">选择</a>

	</td>
	</tr>
	<tr>
		<th>模块样式：</th><td><input type="text" name="css" value="{{menu.css}}" /></td>
	</tr>
	<tr>
		<th></th>
		<td></td>
	</tr>
</table>

</form>
{% endwith %}
{% endblock %}

templates/system/menu_list.html
{% extends "base.html" %}

{% block header%}
<title>功能列表</title>
{% endblock %}

{% block content %}
{% with model_name='Menu' url_prefix='/system/menu/menu_'  %}

<script src="/static/js/treetable/jquery.treetable.js"></script>
<!-- <script src="/static/js/treetable/jquery.treegrid.js"></script> -->
<link href="/static/css/treetable/jquery.treetable.css" rel="stylesheet">

<script type="text/javascript">
	function add{{model_name}}(ele){
		menu_edit()
	}
	function edit{{model_name}}(ele){
		menu_edit(ele)
	}
	function remove{{model_name}}(ele){
		if (confirmRandom('确定删除吗?')){
			window.location.href = "{{url_prefix}}remove?"+$('#{{model_name}}_area :checkbox').serialize()
		}
	}

	function menu_edit(event){
        var fatherBody = $(window.top.document.body);
        fatherBody.find("#temp_modal>#_menu_modal").remove()

        if(!event){
        	//新建
        	$("#menu_modal").find(".modal-title").text("添加");
        	$("#menu_modal").find("input").val("");
        }else{
			$("#menu_modal").find(".modal-title").text($(event).attr("data_name"));
			$("#menu_modal").find("input[name='name']").val($(event).attr("data_name"));
			if(!!$(event).attr("data_parent-id")){
				$("#menu_modal").find("input[name='parent']").val($(event).attr("data_parent-id"));
			}else{
				$("#menu_modal").find("input[name='parent']").val("顶级");
			}
			$("#menu_modal").find("input[name='name']").val($(event).attr("data_name"));
			$("#menu_modal").find("input[name='path']").val($(event).attr("data_url"));
			$("#menu_modal").find("input[name='icon']").val($(event).attr("data_icon"));
		}

		var _menu_modal = $("#menu_modal").clone()
		_menu_modal.attr("id","_menu_modal")
		// $("#menu_modal").appendTo(fatherBody)
		fatherBody.find("#temp_modal").prepend(_menu_modal)
		fatherBody.append("<div id='backdropId' class='modal-backdrop fade in'></div>");
		fatherBody.find("#_menu_modal").modal('show');
	}

	function saveModal(event){
		debugger;
	}
</script>

<div class="modal fade" tabindex="-1" role="dialog"  id="menu_modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
      	<form class="form-horizontal">
      		<div id="editTagConfig" class="modal-body">
                <table id="tags-table" class="table table-condensed table-bordered table-striped table-hover">
	                <tbody>
	                  <tr class="">
	                  	<th>模块名称</th><td><input type="text" name="name"></td>
	                  </tr>
	                  <tr class="">
	                  	<th>父级</th><td><input type="text" name="parent"></td>
	                  </tr>
	                  <tr class="">
	                  	<th>菜单显示：</th>
						<td>
						<input type="checkbox" name="is_show" value="1"  {%ifequal menu.is_show 1%} checked="checked"{%endifequal%}/>
						<!-- <label class="inline">
							<input type="checkbox" value="1" {%ifequal menu.is_show 1%} checked="checked"{%endifequal%} offval="No" id="stock" name="is_show" role="checkbox" class="FormElement ace ace-switch ace-switch-5"><span class="lbl"></span>
						</label> -->
						</td>
	                  </tr>
	                  <tr class="">
	                  	<th>模块路径</th><td><input type="text" name="path" size=50 max_length=30></td>
	                  </tr>
	                  <tr class="">
	                  	<th>模块图标</th><td><input type="text" name="icon"></td>
	                  </tr>
	                </tbody>
	            </table>
            </div>
            </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" id="closeModal" onclick='$("#backdropId").remove();'>关闭</button>
        <button type="button" class="btn btn-primary" id="saveModal" onclick="saveModal(this)" data_url="{{url_prefix}}save">保存配置</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="bar"></div>
<ul id="nav-list" class="nav nav-tabs">
	  <li class="active">
	  	<a href="{{url_prefix}}list" >模块列表</a>
	  </li>
</ul>

<div class="treetable-toolbar">
	<div class="row">
			<div class="col-sm-3"></div>
			<div class="col-sm-9">
				<div class="table_toolbar">
				<div class="btn-toolbar pull-right">
					<div class="btn-group ">
						<a class="btn btn-sm btn-success " onclick="add{{model_name}}(this)">
							<i class="icon-plus-sign"></i>添加
						</a>
					</div>
					<div class="btn-group">
						
						<a class="btn btn-sm btn-primary " onclick="edit{{model_name}}(this)">
							<i class="icon-edit"></i>编辑
						</a>
						<a data-toggle="dropdown" class="btn btn-sm  btn-primary dropdown-toggle">
							<span class="fa fa-caret-down "></span>
						</a>
						<ul class="dropdown-menu">
							<li>
								<a  onclick="remove{{model_name}}(this)">
									<i class="fa fa-trash "></i>
									删除
								</a>
							</li>
						</ul>
					</div>
				</div>
				</div>
			</div>
	</div>
	<table id="{{model_name}}_table" class="table treetable" data-group-by-index='[4,5]'>
		<thead>
		<tr>
			<th >
				<input type="checkbox" checkbox-area='{{model_name}}_area'  >
				<a href="javascript:;" onclick="$(this).closest('.treetable').treetable('expandAll'); return false;">展开</a> 
				<a href="javascript:;" onclick="$(this).closest('.treetable').treetable('collapseAll'); return false;">收缩</a> 
				模块名

			</th>
			<th>路径</th>
			<th>排序</th>
			<th>日志</th>

		</tr>
		</thead>
		<tbody id="{{model_name}}_area">
		{%for item in list_record %}
			<tr data-tt-id="{{item.tt_id}}" data-tt-parent-id="{{item.tt_parent_id}}" trid='{{item.id}}' >
				<td>
					<input type="checkbox"  value="{{item.id}}" name="id">
					{%if item.icon%}<i class="{{item.icon}}" /></i>{%endif%}
					<b style="{{item.css}}" >
					<a href="javascript:;" onclick="menu_edit(this)" data_name="{{item.name}}" data_id="{{item.id}}"
					data_icon="{{item.icon}}" data_parent-id="{{item.tt_parent_id}}" data_tt-id="{{item.tt_id}}" data_url="{{item.url}}" data_isShow="{{item.is_show}}">
					{{item.name}}
					</b>
				</td>
				<td>{{item.url}}</td>
				<td>{{item.order}}</td>
				<td>
					{{item.is_log}}
				</td>

			</tr>
		{%endfor%}
		</tbody>
	</table>
</div>
<script type="text/javascript">
	$(document).ready(function(){
		$('.treetable').treetable();
		$('.treetable').treetable("collapseAll");
	})
</script>
{% endwith %}
{% endblock %}

templates/system/role_list.html
{% extends "base.html" %}

{% block header%}
<title>用户列表</title>
{% endblock %}

{% block content %}
{% with model_name='Admin' url_prefix='/system/admin/admin_' %}
<div >
	<ul id="nav-list" class="nav nav-tabs" >
			  <li  >
			  	<a href="{{url_prefix}}list">用户列表</a>
			  </li>
			  <li class="active">
			  	<a href="/system/role/role_list" data-toggle="tab">角色列表</a>
			  </li>
	</ul>
	<!-- 按钮工具条 -->
	<div id='datatable_toolbar'>
		<div class="btn-toolbar pull-right">
			<div class="btn-group ">
				<a class="btn btn btn-success " onclick="add{{model_name}}(this)">
					<i class="fa fa-plus-square"></i>添加
				</a>
			</div>
			<div class="btn-group">
				
				<a class="btn btn btn-primary " onclick="edit{{model_name}}(this)">
					<i class="fa fa-edit"></i>编辑
				</a>
				<a data-toggle="dropdown" class="btn btn-primary dropdown-toggle">
					<span class="menu-arrow arrow_carrot-down"></span>
				</a>
				<ul class="dropdown-menu">
					<li>
						<a  class="" onclick="remove{{model_name}}(this)">
							<i class="fa fa-trash-o"></i> 删除
						</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
	<span class="clear"></span>
	<!--  -->
	<table class="table table-striped table-advance table-hover table-bordered datatable" data-toolbar='datatable_toolbar' data-group-by-index='[3]'>
		<thead>
		<tr trid='{{item.id}}'>
			<th width="60">
				<input type="checkbox"  checkbox-area='{{model_name}}_area'  >
			</th>
			<th >ID</th>
			<th>角色名</th>
			<th>角色类型</th>

		</tr>
		</thead>
		<tbody id="{{model_name}}_area">
		{%for item in list_record%}
		<tr trid='{{item.id}}'>
			<td>
				<input type="checkbox"  value="{{item.id}}" name="id">
			</td>
			<td>{{item.id}}</td>
			<td title="{{item.remark}}"><a href="{{url_prefix}}edit?id={{item.id}}" class="openDialog">{{item.name}}</a></td>
			<td>{{item.get_type_display}}</td>
		</tr>
		{%endfor%}
		</tbody>
	</table>
</div>
{%endwith%}
{% endblock %}